services:
  - type: web
    name: gamify
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn gamify_ai.wsgi
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.12.0
    staticPublishPath: staticfiles
